name: HTML validator
on:
  push:
    branches:
      - main
      - master
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: anishathalye/proof-html@v1
        with:
          directory: ./
